{% set version = "1.0.8" %}

package:
  name: spglm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spglm/spglm-{{ version }}.tar.gz
  sha256: df83b8f7caa41c8aebc4cc39179e40e8670783b06ee567b59bbbe818b773f300

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - libpysal >=4.0.0
    - numpy >=1.3
    - scipy >=0.11
    - spreg >=1.0.4

test:
  imports:
    - spglm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/spglm
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Sparse generalized linear models

extra:
  recipe-maintainers:
    - knaaptime
    - martinfleis
    - jGaboardi
    - ocefpaf
